# -*- coding: utf-8 -*-
"""Descrições curadas (nomen juris) para dispositivos sem rubrica no texto oficial
ou cuja rubrica automática ficaria pobre. Chave = idUnico."""

DESC = {
    # ---------------- Código Penal – artigos sem rubrica ----------------
    "CP:126": "Aborto provocado por terceiro com consentimento da gestante",
    "CP:128": "Aborto legal (necessário ou de gravidez resultante de estupro) – não punível",
    "CP:135-A": "Condicionamento de atendimento médico-hospitalar emergencial",
    "CP:141": "Crimes contra a honra – causas de aumento de pena",
    "CP:143": "Retratação (calúnia ou difamação)",
    "CP:144": "Pedido de explicações (crimes contra a honra)",
    "CP:145": "Ação penal nos crimes contra a honra",
    "CP:147-C": "Ameaça no contexto de organização criminosa ultraviolenta, grupo paramilitar ou milícia",
    "CP:170": "Crimes de apropriação indébita – aplicação do furto privilegiado",
    "CP:171-A": "Fraude com ativos virtuais (criptoativos) – organização ou oferta de carteiras e operações",
    "CP:181": "Isenção de pena nos crimes contra o patrimônio (imunidade absoluta)",
    "CP:182": "Ação penal mediante representação nos crimes contra o patrimônio (imunidade relativa)",
    "CP:183": "Inaplicabilidade das imunidades patrimoniais",
    "CP:183-A": "Crimes contra o patrimônio praticados contra instituições financeiras e segurança privada",
    "CP:186": "Ação penal nos crimes contra a propriedade imaterial",
    "CP:218-B": "Favorecimento da prostituição ou de outra forma de exploração sexual de criança, adolescente ou vulnerável",
    "CP:234-B": "Segredo de justiça nos crimes contra a dignidade sexual",
    "CP:247": "Abandono moral",
    "CP:268": "Infração de medida sanitária preventiva",
    "CP:295": "Crimes de moeda falsa – aumento de pena para funcionário público",
    "CP:308": "Uso de documento de identidade alheia",
    "CP:310": "Simulação de propriedade de bens vedados a estrangeiro (testa de ferro)",
    "CP:319-A": "Prevaricação imprópria (omissão do diretor de penitenciária – aparelhos telefônicos)",
    "CP:337-P": "Pena de multa nos crimes em licitações e contratos administrativos",
    "CP:343": "Corrupção ativa de testemunha, perito, contador, tradutor ou intérprete",
    "CP:346": "Exercício arbitrário das próprias razões – subtração de coisa própria em poder de terceiro",
    "CP:349-A": "Ingresso de aparelho telefônico de comunicação móvel em estabelecimento prisional",
    "CP:359-M-A": "Crimes contra o Estado Democrático de Direito – concurso de crimes no mesmo contexto",
    "CP:359-M-B": "Crimes contra o Estado Democrático de Direito – redução de pena em contexto de multidão",
    "CP:359-T": "Manifestação crítica, atividade jornalística e reivindicação de direitos não constituem crime",
    "CP:360": "Disposições finais – ressalva da legislação especial",
    "CP:361": "Vigência do Código Penal",
    # ---------------- Código Penal – parágrafos mais citados ----------------
    "CP:121.1": "Homicídio privilegiado (relevante valor social ou moral / violenta emoção)",
    "CP:121.2": "Homicídio qualificado",
    "CP:121.2-B": "Homicídio contra menor de 14 anos – causas de aumento",
    "CP:121.2-C": "Homicídio em instituição de ensino – causas de aumento",
    "CP:121.2-D": "Homicídio por integrante de organização criminosa ultraviolenta, grupo paramilitar ou milícia",
    "CP:121.3": "Homicídio culposo",
    "CP:121.4": "Homicídio – causas de aumento de pena (culposo e doloso)",
    "CP:121.5": "Homicídio culposo – perdão judicial",
    "CP:121.6": "Homicídio praticado por milícia privada ou grupo de extermínio (aumento)",
    "CP:121-A.1": "Feminicídio – razões da condição do sexo feminino",
    "CP:121-A.2": "Feminicídio – causas de aumento de pena",
    "CP:121-A.3": "Feminicídio – comunicabilidade das circunstâncias ao coautor",
    "CP:121-B.1": "Vicaricídio – causas de aumento de pena",
    "CP:122.1": "Induzimento a suicídio ou automutilação – resultado lesão corporal grave ou gravíssima",
    "CP:122.2": "Induzimento a suicídio ou automutilação – resultado morte",
    "CP:122.3": "Induzimento a suicídio ou automutilação – pena duplicada",
    "CP:122.4": "Induzimento a suicídio ou automutilação pela internet ou redes sociais (aumento)",
    "CP:122.5": "Induzimento a suicídio – líder de grupo ou rede virtual (pena em dobro)",
    "CP:126.1": "Aborto consentido – gestante menor de 14 anos ou incapaz (equiparação)",
    "CP:129.1": "Lesão corporal grave",
    "CP:129.2": "Lesão corporal gravíssima",
    "CP:129.3": "Lesão corporal seguida de morte",
    "CP:129.3-A": "Lesão corporal seguida de morte por integrante de organização criminosa ultraviolenta",
    "CP:129.4": "Lesão corporal privilegiada (diminuição de pena)",
    "CP:129.5": "Lesão corporal – substituição da pena por multa",
    "CP:129.6": "Lesão corporal culposa",
    "CP:129.7": "Lesão corporal – aumento de pena",
    "CP:129.8": "Lesão corporal culposa – perdão judicial",
    "CP:129.9": "Lesão corporal no contexto de violência doméstica",
    "CP:129.10": "Lesão corporal grave, gravíssima ou seguida de morte em violência doméstica (aumento)",
    "CP:129.11": "Violência doméstica contra pessoa com deficiência (aumento)",
    "CP:129.12": "Lesão corporal contra agentes de segurança pública e seus familiares (aumento)",
    "CP:129.13": "Lesão corporal contra a mulher por razões da condição do sexo feminino",
    "CP:130.1": "Perigo de contágio venéreo – intenção de transmitir a moléstia",
    "CP:133.1": "Abandono de incapaz com resultado lesão corporal grave",
    "CP:133.2": "Abandono de incapaz com resultado morte",
    "CP:133.3": "Abandono de incapaz – causas de aumento de pena",
    "CP:134.1": "Exposição ou abandono de recém-nascido com resultado lesão corporal grave",
    "CP:134.2": "Exposição ou abandono de recém-nascido com resultado morte",
    "CP:136.1": "Maus-tratos com resultado lesão corporal grave",
    "CP:136.2": "Maus-tratos com resultado morte",
    "CP:136.3": "Maus-tratos contra menor de 14 anos (aumento)",
    "CP:137.1": "Rixa qualificada (resultado morte ou lesão corporal grave)",
    "CP:138.1": "Calúnia – propalação ou divulgação",
    "CP:138.2": "Calúnia contra os mortos",
    "CP:138.3": "Calúnia – exceção da verdade",
    "CP:139.1": "Difamação – exceção da verdade",
    "CP:140.1": "Injúria – perdão judicial",
    "CP:140.2": "Injúria real (violência ou vias de fato)",
    "CP:140.3": "Injúria discriminatória (religião, condição de pessoa idosa ou com deficiência)",
    "CP:141.1": "Crimes contra a honra mediante paga ou promessa de recompensa (pena em dobro)",
    "CP:141.2": "Crimes contra a honra cometidos ou divulgados em redes sociais (pena em triplo)",
    "CP:141.3": "Crimes contra a honra contra a mulher por razões da condição do sexo feminino",
    "CP:146.1": "Constrangimento ilegal – concurso de pessoas ou emprego de armas (aumento)",
    "CP:146.2": "Constrangimento ilegal – cumulação com as penas da violência",
    "CP:146.3": "Constrangimento ilegal – exclusão (intervenção médica e coação para impedir suicídio)",
    "CP:147.1": "Ameaça contra a mulher por razões da condição do sexo feminino",
    "CP:147.2": "Ameaça – ação penal (representação)",
    "CP:147-A.1": "Perseguição (stalking) – causas de aumento de pena",
    "CP:148.1": "Sequestro e cárcere privado qualificado",
    "CP:148.2": "Sequestro e cárcere privado com grave sofrimento físico ou moral",
    "CP:148.3": "Sequestro e cárcere privado por integrante de organização criminosa ultraviolenta",
    "CP:149.1": "Redução a condição análoga à de escravo – condutas equiparadas",
    "CP:149.2": "Redução a condição análoga à de escravo – causas de aumento de pena",
    "CP:149-A.1": "Tráfico de pessoas – causas de aumento de pena",
    "CP:149-A.2": "Tráfico de pessoas – redução de pena (agente primário)",
    "CP:150.1": "Violação de domicílio qualificada (noite, lugar ermo, violência ou arma)",
    "CP:150.3": "Violação de domicílio – exclusão de crime",
    "CP:150.4": "Violação de domicílio – conceito de casa",
    "CP:150.5": "Violação de domicílio – o que não se compreende na expressão casa",
    "CP:151.1": "Sonegação ou destruição de correspondência / violação de comunicação",
    "CP:151.3": "Violação de correspondência com abuso de função (serviço postal ou telefônico)",
    "CP:153.1-A": "Divulgação de informações sigilosas ou reservadas da Administração Pública",
    "CP:154-A.1": "Invasão de dispositivo informático – produção ou difusão de programa invasor",
    "CP:154-A.2": "Invasão de dispositivo informático – aumento por prejuízo econômico",
    "CP:154-A.3": "Invasão de dispositivo informático qualificada (comunicações privadas, segredos, controle remoto)",
    "CP:154-A.4": "Invasão de dispositivo informático – aumento por divulgação ou comercialização dos dados",
    "CP:154-A.5": "Invasão de dispositivo informático – aumento (vítima autoridade pública)",
    "CP:155.1": "Furto durante o repouso noturno",
    "CP:155.2": "Furto privilegiado",
    "CP:155.3": "Furto de energia elétrica ou de outra com valor econômico (equiparação)",
    "CP:155.4": "Furto qualificado",
    "CP:155.4-A": "Furto com emprego de explosivo ou artefato análogo",
    "CP:155.4-B": "Furto mediante fraude eletrônica",
    "CP:155.4-C": "Furto mediante fraude eletrônica – causas de aumento de pena",
    "CP:155.5": "Furto de veículo automotor transportado para outro Estado ou para o exterior",
    "CP:155.6": "Furto de semovente domesticável ou de aparelho celular/dispositivo eletrônico",
    "CP:155.7": "Furto de substâncias explosivas ou de arma de fogo",
    "CP:155.8": "Furto de fios, cabos e equipamentos de energia ou telecomunicações",
    "CP:155.9": "Furto por integrante de organização criminosa ultraviolenta, grupo paramilitar ou milícia",
    "CP:155.10": "Furto de petróleo, derivados, gás natural e combustíveis",
    "CP:155.11": "Furto de combustíveis – causas de aumento de 1/3",
    "CP:155.12": "Furto de combustíveis – causas de aumento de 2/3",
    "CP:156.1": "Furto de coisa comum – ação penal (representação)",
    "CP:156.2": "Furto de coisa comum fungível – não punibilidade",
    "CP:157.1": "Roubo impróprio",
    "CP:157.1-A": "Roubo contra bens que comprometam o funcionamento de órgãos públicos",
    "CP:157.2": "Roubo circunstanciado (aumento de 1/3 até metade)",
    "CP:157.2-A": "Roubo com emprego de arma de fogo ou explosivo (aumento de 2/3)",
    "CP:157.2-B": "Roubo com arma de fogo de uso restrito ou proibido (pena em dobro)",
    "CP:157.3": "Roubo qualificado pelo resultado (lesão corporal grave ou morte)",
    "CP:157.3.I": "Roubo com lesão corporal grave",
    "CP:157.3.II": "Latrocínio",
    "CP:157.4": "Roubo por integrante de organização criminosa ultraviolenta, grupo paramilitar ou milícia",
    "CP:157.5": "Latrocínio por integrante de organização criminosa ultraviolenta, grupo paramilitar ou milícia",
    "CP:158.1": "Extorsão com concurso de pessoas ou emprego de arma (aumento)",
    "CP:158.2": "Extorsão com violência – aplicação do § 3º do art. 157",
    "CP:158.3": "Sequestro relâmpago (extorsão com restrição da liberdade da vítima)",
    "CP:158.4": "Extorsão por integrante de organização criminosa ultraviolenta, grupo paramilitar ou milícia",
    "CP:159.1": "Extorsão mediante sequestro qualificada (duração, vítima menor ou idosa, bando)",
    "CP:159.2": "Extorsão mediante sequestro com lesão corporal grave",
    "CP:159.3": "Extorsão mediante sequestro com resultado morte",
    "CP:159.4": "Extorsão mediante sequestro – delação premiada (redução de pena)",
    "CP:159.5": "Extorsão mediante sequestro por integrante de organização criminosa ultraviolenta",
    "CP:161.1": "Alteração de limites – usurpação de águas e esbulho possessório",
    "CP:163.1": "Dano qualificado",
    "CP:168.1": "Apropriação indébita – causas de aumento de pena",
    "CP:168-A.1": "Apropriação indébita previdenciária – condutas equiparadas",
    "CP:168-A.2": "Apropriação indébita previdenciária – extinção da punibilidade pelo pagamento",
    "CP:168-A.3": "Apropriação indébita previdenciária – perdão judicial ou multa",
    "CP:169.1": "Apropriação de tesouro ou de coisa achada",
    "CP:171.1": "Estelionato privilegiado",
    "CP:171.2": "Estelionato – figuras equiparadas (disposição de coisa alheia, defraudação de penhor, fraude no pagamento por cheque)",
    "CP:171.2-A": "Fraude eletrônica",
    "CP:171.2-B": "Fraude eletrônica – causas de aumento de pena",
    "CP:171.3": "Estelionato contra entidade de direito público ou de assistência social (aumento)",
    "CP:171.4": "Estelionato contra idoso ou vulnerável (aumento)",
    "CP:171.5": "Estelionato – ação penal (representação)",
    "CP:175.1": "Fraude no comércio – alteração de metal ou pedra preciosa em obra encomendada",
    "CP:177.1": "Fraudes na administração de sociedade por ações – condutas equiparadas",
    "CP:177.2": "Fraude do acionista na negociação de voto",
    "CP:180.1": "Receptação qualificada",
    "CP:180.2": "Receptação – equiparação à atividade comercial",
    "CP:180.3": "Receptação culposa",
    "CP:180.4": "Receptação – punibilidade autônoma",
    "CP:180.6": "Receptação de bens do patrimônio público (pena em dobro)",
    "CP:180.7": "Receptação de fios, cabos e equipamentos de energia ou telecomunicações",
    "CP:180.8": "Receptação por integrante de organização criminosa ultraviolenta, grupo paramilitar ou milícia",
    "CP:184.1": "Violação de direito autoral com intuito de lucro (reprodução)",
    "CP:184.2": "Violação de direito autoral – distribuição, venda ou aluguel de cópia",
    "CP:184.3": "Violação de direito autoral – oferecimento ao público por meios eletrônicos",
    "CP:184.4": "Violação de direito autoral – exceções e limitações",
    "CP:213.1": "Estupro qualificado (lesão corporal grave ou vítima entre 14 e 18 anos)",
    "CP:213.2": "Estupro com resultado morte",
    "CP:215.1": "Violação sexual mediante fraude com fim de vantagem econômica (multa)",
    "CP:216-A.2": "Assédio sexual contra menor de 18 anos (aumento)",
    "CP:216-B.1": "Registro não autorizado da intimidade sexual – montagem",
    "CP:217-A.1": "Estupro de vulnerável (enfermo ou deficiente mental / pessoa sem capacidade de resistência)",
    "CP:217-A.3": "Estupro de vulnerável com lesão corporal grave",
    "CP:217-A.4": "Estupro de vulnerável com resultado morte",
    "CP:217-A.4-A": "Estupro de vulnerável – presunção absoluta de vulnerabilidade",
    "CP:217-A.5": "Estupro de vulnerável – irrelevância do consentimento da vítima",
    "CP:218-B.2": "Favorecimento da prostituição de vulnerável – figuras equiparadas (cliente e responsável pelo local)",
    "CP:218-B.3": "Favorecimento da prostituição de vulnerável – cassação da licença do estabelecimento",
    "CP:218-C.1": "Divulgação de cena de estupro ou de sexo – aumento de pena",
    "CP:218-C.2": "Divulgação de cena de estupro ou de sexo – exclusão de ilicitude",
    "CP:226": "Crimes contra a dignidade sexual – causas de aumento de pena",
    "CP:227.1": "Mediação para servir a lascívia – vítima entre 14 e 18 anos ou parentesco (qualificada)",
    "CP:227.2": "Mediação para servir a lascívia com violência, grave ameaça ou fraude",
    "CP:228.1": "Favorecimento da prostituição qualificado (parentesco ou autoridade sobre a vítima)",
    "CP:228.2": "Favorecimento da prostituição com violência, grave ameaça ou fraude",
    "CP:230.1": "Rufianismo qualificado (vítima entre 14 e 18 anos ou parentesco)",
    "CP:230.2": "Rufianismo com violência, grave ameaça ou fraude",
    "CP:232-A.1": "Promoção de migração ilegal – saída de estrangeiro do território nacional",
    "CP:232-A.2": "Promoção de migração ilegal – causas de aumento de pena",
    "CP:234-A": "Crimes contra a dignidade sexual – causas de aumento de pena (gravidez, doença)",
    "CP:235.1": "Bigamia – contraente não casado",
    "CP:242.1": "Parto suposto por motivo de reconhecida nobreza (privilegiado)",
    "CP:244.1": "Abandono material – frustração do pagamento de pensão alimentícia",
    "CP:245.1": "Entrega de filho menor a pessoa inidônea para obter lucro ou envio ao exterior",
    "CP:250.1": "Incêndio – causas de aumento de pena",
    "CP:250.2": "Incêndio culposo",
    "CP:251.1": "Explosão com substância diversa de dinamite",
    "CP:251.2": "Explosão – causas de aumento de pena",
    "CP:251.3": "Explosão culposa",
    "CP:252.1": "Uso de gás tóxico ou asfixiante – modalidade culposa",
    "CP:256.1": "Desabamento ou desmoronamento – modalidade culposa",
    "CP:259.1": "Difusão de doença ou praga – modalidade culposa",
    "CP:260.1": "Desastre ferroviário",
    "CP:260.2": "Desastre ferroviário culposo",
    "CP:261.1": "Sinistro em transporte marítimo, fluvial ou aéreo",
    "CP:261.3": "Atentado contra a segurança de transporte – modalidade culposa",
    "CP:262.1": "Atentado contra a segurança de outro meio de transporte com desastre",
    "CP:262.2": "Atentado contra a segurança de outro meio de transporte – modalidade culposa",
    "CP:267.1": "Epidemia com resultado morte",
    "CP:267.2": "Epidemia culposa",
    "CP:270.1": "Envenenamento – entrega a consumo de água ou substância envenenada",
    "CP:270.2": "Envenenamento de água ou substância alimentícia – modalidade culposa",
    "CP:271.1": "Corrupção ou poluição de água potável – modalidade culposa",
    "CP:272.1": "Falsificação de produto alimentício – bebidas (equiparação)",
    "CP:272.1-A": "Falsificação de produto alimentício – fabricação, venda ou depósito",
    "CP:272.2": "Falsificação de produto alimentício – modalidade culposa",
    "CP:273.1": "Falsificação de medicamento – importação, venda ou depósito",
    "CP:273.1-A": "Falsificação de medicamento – produtos abrangidos (medicamentos, cosméticos, saneantes)",
    "CP:273.1-B": "Falsificação de medicamento – produto sem registro ou de procedência ignorada",
    "CP:273.2": "Falsificação de medicamento – modalidade culposa",
    "CP:278.1": "Outras substâncias nocivas à saúde pública – modalidade culposa",
    "CP:280.1": "Medicamento em desacordo com receita médica – modalidade culposa",
    "CP:288.1": "Associação criminosa armada ou com participação de criança ou adolescente (aumento)",
    "CP:288.2": "Associação criminosa – solicitação ou contratação de crime a integrante",
    "CP:289.1": "Moeda falsa – importação, exportação, circulação e guarda",
    "CP:289.2": "Moeda falsa recebida de boa-fé – restituição à circulação",
    "CP:289.3": "Moeda falsa – fabricação ou emissão irregular por funcionário público ou diretor de instituição",
    "CP:289.4": "Moeda falsa – desvio e circulação de moeda não autorizada",
    "CP:293.1": "Falsificação de papéis públicos – uso, importação, venda e depósito",
    "CP:293.2": "Falsificação de papéis públicos – supressão de sinal de inutilização",
    "CP:296.1": "Falsificação de selo ou sinal público – uso indevido e falsificação de símbolos oficiais",
    "CP:296.2": "Falsificação de selo ou sinal público por funcionário público (aumento)",
    "CP:297.1": "Falsificação de documento público por funcionário público (aumento)",
    "CP:297.2": "Falsificação de documento público – equiparação a documento público",
    "CP:297.3": "Falsificação de documento público – inserção de declaração falsa em documentos previdenciários",
    "CP:297.4": "Falsificação de documento público – omissão em documentos previdenciários",
    "CP:298.1": "Falsificação de cartão de crédito ou débito",
    "CP:299.1": "Falsidade ideológica por funcionário público ou em assentamento de registro civil (aumento)",
    "CP:301.1": "Falsidade material de atestado ou certidão",
    "CP:301.2": "Falsidade de atestado ou certidão com fim de lucro (multa)",
    "CP:306.1": "Falsificação de marca ou sinal de fiscalização sanitária (equiparação)",
    "CP:309.1": "Fraude de lei sobre estrangeiro – atribuição de falsa qualidade a estrangeiro",
    "CP:311.1": "Adulteração de sinal identificador de veículo por funcionário público (aumento)",
    "CP:311.2": "Adulteração de sinal identificador de veículo – condutas equiparadas",
    "CP:311.3": "Adulteração de sinal identificador de veículo no exercício de atividade comercial (qualificada)",
    "CP:311-A.1": "Fraude em certame – facilitação de acesso a conteúdo sigiloso",
    "CP:311-A.2": "Fraude em certame com dano à Administração Pública (qualificada)",
    "CP:311-A.3": "Fraude em certame cometida por funcionário público (aumento)",
    "CP:312.1": "Peculato-furto (subtração por funcionário público)",
    "CP:312.2": "Peculato culposo",
    "CP:312.3": "Peculato culposo – reparação do dano (extinção da punibilidade)",
    "CP:313-B.1": "Modificação não autorizada de sistema de informações com dano (aumento)",
    "CP:316.1": "Excesso de exação",
    "CP:316.2": "Excesso de exação qualificado (desvio do recebido)",
    "CP:317.1": "Corrupção passiva – aumento (ato de ofício retardado, omitido ou praticado com infração de dever)",
    "CP:317.2": "Corrupção passiva privilegiada",
    "CP:321.1": "Advocacia administrativa com interesse ilegítimo",
    "CP:323.1": "Abandono de função com prejuízo público",
    "CP:323.2": "Abandono de função em faixa de fronteira",
    "CP:325.1": "Violação de sigilo funcional – sistemas de informação da Administração",
    "CP:325.2": "Violação de sigilo funcional com dano à Administração ou a outrem",
    "CP:327.1": "Funcionário público por equiparação",
    "CP:327.2": "Crimes funcionais – aumento para ocupantes de cargo em comissão ou função de direção",
    "CP:328.1": "Usurpação de função pública com proveito (qualificada)",
    "CP:329.1": "Resistência qualificada (ato não executado)",
    "CP:332.1": "Tráfico de influência – aumento (insinuação de destinação da vantagem ao funcionário)",
    "CP:333.1": "Corrupção ativa – aumento (ato de ofício retardado, omitido ou praticado com infração de dever)",
    "CP:334.1": "Descaminho – condutas equiparadas",
    "CP:334.2": "Descaminho – equiparação à atividade comercial",
    "CP:334.3": "Descaminho em transporte aéreo, marítimo ou fluvial (pena em dobro)",
    "CP:334-A.1": "Contrabando – condutas equiparadas",
    "CP:334-A.2": "Contrabando – equiparação à atividade comercial",
    "CP:334-A.3": "Contrabando em transporte aéreo, marítimo ou fluvial (pena em dobro)",
    "CP:337-A.1": "Sonegação de contribuição previdenciária – extinção da punibilidade",
    "CP:337-A.2": "Sonegação de contribuição previdenciária – perdão judicial ou multa",
    "CP:337-M.1": "Celebração de contrato com empresa ou profissional inidôneo",
    "CP:338-A.1": "Descumprimento de medidas protetivas de urgência – competência do juiz",
    "CP:339.1": "Denunciação caluniosa com anonimato ou nome suposto (aumento)",
    "CP:339.2": "Denunciação caluniosa de contravenção (diminuição)",
    "CP:342.1": "Falso testemunho mediante suborno ou em processo penal (aumento)",
    "CP:342.2": "Falso testemunho – retratação",
    "CP:345.1": "Exercício arbitrário das próprias razões – ação penal (queixa)",
    "CP:347.1": "Fraude processual em processo penal (pena em dobro)",
    "CP:348.1": "Favorecimento pessoal – crime apenado com detenção",
    "CP:348.2": "Favorecimento pessoal – isenção de pena (parentes)",
    "CP:351.1": "Fuga de pessoa presa – mão armada, concurso de pessoas ou arrombamento (aumento)",
    "CP:351.2": "Fuga de pessoa presa com violência – cumulação de penas",
    "CP:351.3": "Fuga de pessoa presa facilitada por quem tem a custódia ou guarda",
    "CP:351.4": "Fuga de pessoa presa – culpa do funcionário incumbido da custódia",
    "CP:359-I.2": "Atentado à soberania – participação em operação bélica",
    "CP:359-K.1": "Espionagem – auxílio a espião",
    "CP:359-K.2": "Espionagem com violação do dever de sigilo",
    "CP:359-K.3": "Espionagem – facilitação mediante acesso a sistema informatizado",
    # ---------------- Lei de Drogas ----------------
    "DRG:28": "Porte de drogas para consumo pessoal",
    "DRG:28.1": "Cultivo de plantas para consumo pessoal",
    "DRG:33": "Tráfico de drogas",
    "DRG:33.1": "Tráfico de drogas – condutas equiparadas (matéria-prima, cultivo, uso de local)",
    "DRG:33.2": "Induzimento, instigação ou auxílio ao uso indevido de droga",
    "DRG:33.3": "Cessão gratuita de droga para consumo compartilhado (uso compartilhado)",
    "DRG:33.4": "Tráfico privilegiado (redução de pena)",
    "DRG:34": "Tráfico de maquinário, aparelho ou objeto para fabricação de drogas",
    "DRG:35": "Associação para o tráfico",
    "DRG:36": "Financiamento ou custeio do tráfico",
    "DRG:37": "Colaboração como informante do tráfico",
    "DRG:38": "Prescrição ou ministração culposa de drogas",
    "DRG:39": "Condução de embarcação ou aeronave após o consumo de drogas",
    "DRG:40": "Tráfico de drogas – causas de aumento de pena (arts. 33 a 37)",
    "DRG:40-A": "Tráfico de drogas – aplicação da pena em dobro (arts. 33 a 37)",
    "DRG:41": "Colaboração voluntária com a investigação (redução de pena)",
    # ---------------- Lei de Crimes Ambientais ----------------
    "AMB:29": "Crime contra a fauna silvestre (matar, caçar, apanhar ou utilizar espécimes)",
    "AMB:29.1": "Crime contra a fauna – condutas equiparadas",
    "AMB:29.4": "Crime contra a fauna – causas de aumento de pena",
    "AMB:29.5": "Crime contra a fauna – caça profissional (aumento até o triplo)",
    "AMB:30": "Exportação ilegal de peles e couros de anfíbios e répteis",
    "AMB:31": "Introdução de espécime animal no País sem licença",
    "AMB:32": "Maus-tratos a animais",
    "AMB:32.1": "Maus-tratos a animais – experiência dolorosa ou cruel em animal vivo",
    "AMB:32.1-A": "Maus-tratos a cão ou gato",
    "AMB:32.2": "Maus-tratos a animais com resultado morte (aumento)",
    "AMB:33": "Perecimento de espécimes da fauna aquática por poluição",
    "AMB:34": "Pesca em período ou local proibido",
    "AMB:35": "Pesca com explosivos ou substâncias tóxicas",
    "AMB:36": "Definição de pesca",
    "AMB:37": "Abate de animal não criminoso (estado de necessidade e animal nocivo)",
    "AMB:38": "Destruição ou dano a floresta de preservação permanente",
    "AMB:38.1": "Destruição ou dano a floresta de preservação permanente – modalidade culposa",
    "AMB:38-A": "Destruição ou dano a vegetação do Bioma Mata Atlântica",
    "AMB:38-A.1": "Destruição ou dano a vegetação do Bioma Mata Atlântica – modalidade culposa",
    "AMB:39": "Corte de árvores em floresta de preservação permanente",
    "AMB:40": "Dano a Unidades de Conservação",
    "AMB:41": "Incêndio em floresta ou demais formas de vegetação",
    "AMB:41.1": "Incêndio em floresta ou vegetação – modalidade culposa",
    "AMB:42": "Fabricação, venda, transporte ou soltura de balões",
    "AMB:44": "Extração ilegal de minerais em florestas de domínio público ou de preservação permanente",
    "AMB:45": "Corte ou transformação em carvão de madeira de lei",
    "AMB:46": "Recebimento ou aquisição de produto florestal sem licença",
    "AMB:48": "Impedimento ou dificultação da regeneração natural de florestas",
    "AMB:49": "Destruição ou dano a plantas de ornamentação",
    "AMB:50": "Destruição de florestas nativas ou de vegetação fixadora de dunas e mangues",
    "AMB:50-A": "Desmatamento ou degradação de floresta em terras de domínio público ou devolutas",
    "AMB:51": "Comercialização ou uso de motosserra sem licença",
    "AMB:52": "Ingresso em Unidade de Conservação com instrumentos de caça ou exploração",
    "AMB:53": "Crimes contra a flora – causas de aumento de pena",
    "AMB:54": "Poluição",
    "AMB:54.1": "Poluição culposa",
    "AMB:54.2": "Poluição qualificada",
    "AMB:54.3": "Omissão de medidas de precaução em caso de risco de dano ambiental grave",
    "AMB:55": "Pesquisa, lavra ou extração mineral sem autorização",
    "AMB:56": "Produção, comercialização, transporte ou armazenamento de substância tóxica ou perigosa",
    "AMB:58": "Crimes de poluição – causas de aumento de pena",
    "AMB:60": "Estabelecimento, obra ou atividade potencialmente poluidora sem licença",
    "AMB:61": "Disseminação de doença, praga ou espécies nocivas",
    "AMB:62": "Destruição ou deterioração de bem especialmente protegido (patrimônio cultural)",
    "AMB:63": "Alteração de edificação ou local especialmente protegido",
    "AMB:64": "Construção em solo não edificável",
    "AMB:65": "Pichação de edificação ou monumento urbano",
    "AMB:66": "Afirmação falsa ou omissão em procedimento ambiental por funcionário público",
    "AMB:67": "Concessão ilegal de licença, autorização ou permissão ambiental",
    "AMB:68": "Omissão de cumprimento de obrigação de relevante interesse ambiental",
    "AMB:69": "Obstrução à fiscalização ambiental",
    "AMB:69-A": "Laudo, estudo ou relatório ambiental falso ou enganoso",
    # ---------------- ECA ----------------
    "ECA:225": "Disposição geral – crimes contra a criança e o adolescente",
    "ECA:226": "Aplicação das normas da Parte Geral do Código Penal",
    "ECA:226-A": "Crimes contra a criança e o adolescente – aumento de pena (modulador de voz ou tecnologia de ocultação)",
    "ECA:227": "Ação penal pública incondicionada",
    "ECA:227-A": "Efeitos da condenação (perda do cargo, mandato ou função)",
    "ECA:227-B": "Direito da vítima de violência sexual a atendimento especializado",
    "ECA:227-C": "Obrigação do agressor de custear tratamento da vítima de violência",
    "ECA:228": "Omissão de registro de atividades e de identificação de neonato pelo estabelecimento de saúde",
    "ECA:229": "Omissão de identificação de neonato e parturiente por médico ou enfermeiro",
    "ECA:230": "Privação ilegal de liberdade de criança ou adolescente (apreensão ilegal)",
    "ECA:231": "Omissão de comunicação de apreensão de criança ou adolescente à autoridade judiciária",
    "ECA:232": "Submissão de criança ou adolescente a vexame ou constrangimento",
    "ECA:234": "Omissão de liberação de criança ou adolescente ilegalmente apreendido",
    "ECA:235": "Descumprimento de prazo em benefício de adolescente privado de liberdade",
    "ECA:236": "Impedimento ou embaraço à ação de autoridade judiciária, Conselho Tutelar ou Ministério Público",
    "ECA:237": "Subtração de criança ou adolescente para colocação em lar substituto",
    "ECA:238": "Promessa ou entrega de filho ou pupilo mediante paga ou recompensa",
    "ECA:239": "Envio ilegal de criança ou adolescente para o exterior",
    "ECA:240": "Produção de conteúdo de violência sexual envolvendo criança ou adolescente",
    "ECA:241": "Venda de conteúdo de violência sexual envolvendo criança ou adolescente",
    "ECA:241-A": "Divulgação ou compartilhamento de conteúdo de violência sexual envolvendo criança ou adolescente",
    "ECA:241-B": "Posse ou armazenamento de conteúdo de violência sexual envolvendo criança ou adolescente",
    "ECA:241-C": "Simulação de participação de criança ou adolescente em conteúdo de violência sexual (montagem)",
    "ECA:241-D": "Aliciamento de criança para fim libidinoso",
    "ECA:241-E": "Definição de conteúdo de violência sexual envolvendo criança ou adolescente",
    "ECA:242": "Venda ou entrega de arma, munição ou explosivo a criança ou adolescente",
    "ECA:243": "Venda ou fornecimento de bebida alcoólica ou produto causador de dependência a criança ou adolescente",
    "ECA:244": "Venda ou fornecimento de fogos de artifício a criança ou adolescente",
    "ECA:244-A": "Submissão de criança ou adolescente à exploração sexual",
    "ECA:244-B": "Corrupção de menores (prática de infração penal com menor de 18 anos)",
    "ECA:244-C": "Omissão dolosa de comunicação de desaparecimento de criança ou adolescente",
    # ---------------- CTB ----------------
    "CTB:165": "Dirigir sob a influência de álcool (infração administrativa – ver crime do art. 306)",
    "CTB:302": "Homicídio culposo na direção de veículo automotor",
    "CTB:302.1": "Homicídio culposo no trânsito – causas de aumento de pena",
    "CTB:302.3": "Homicídio culposo no trânsito sob influência de álcool ou substância psicoativa",
    "CTB:303": "Lesão corporal culposa na direção de veículo automotor",
    "CTB:303.1": "Lesão corporal culposa no trânsito – causas de aumento de pena",
    "CTB:303.2": "Lesão corporal culposa grave no trânsito sob influência de álcool ou substância psicoativa",
    "CTB:304": "Omissão de socorro no trânsito",
    "CTB:305": "Fuga do local do acidente (afastar-se do local do sinistro)",
    "CTB:306": "Embriaguez ao volante (conduzir sob influência de álcool ou substância psicoativa)",
    "CTB:307": "Violação de suspensão ou proibição de dirigir",
    "CTB:308": "Racha (corrida, disputa ou competição automobilística não autorizada)",
    "CTB:308.1": "Racha com resultado lesão corporal grave",
    "CTB:308.2": "Racha com resultado morte",
    "CTB:309": "Direção sem habilitação gerando perigo de dano",
    "CTB:310": "Entrega de veículo a pessoa não habilitada",
    "CTB:311": "Velocidade incompatível com a segurança em locais sensíveis",
    "CTB:312": "Fraude processual em sinistro de trânsito (inovação artificiosa)",
    "CTB:312-A": "Prestação de serviço à comunidade nos crimes de trânsito",
    "CTB:312-B": "Vedação de substituição de pena (art. 302 § 3º e art. 303 § 2º)",
    # ---------------- CDC ----------------
    "CDC:61": "Disposição geral – crimes contra as relações de consumo",
    "CDC:63": "Omissão de dizeres ou sinais sobre nocividade ou periculosidade de produtos",
    "CDC:64": "Omissão de comunicação de nocividade ou periculosidade de produtos",
    "CDC:65": "Execução de serviço de alto grau de periculosidade contra determinação da autoridade",
    "CDC:66": "Afirmação falsa ou enganosa sobre produtos ou serviços",
    "CDC:67": "Publicidade enganosa ou abusiva",
    "CDC:68": "Publicidade capaz de induzir comportamento prejudicial à saúde ou segurança",
    "CDC:69": "Omissão de organização de dados que embasam a publicidade",
    "CDC:70": "Emprego de peças usadas na reparação sem autorização do consumidor",
    "CDC:71": "Cobrança abusiva de dívidas (ameaça, coação ou constrangimento)",
    "CDC:72": "Impedimento de acesso do consumidor a informações em cadastros",
    "CDC:73": "Omissão de correção de informação inexata sobre consumidor",
    "CDC:74": "Omissão de entrega do termo de garantia",
    "CDC:75": "Concurso de pessoas (diretor, administrador ou gerente)",
    "CDC:76": "Circunstâncias agravantes",
    "CDC:77": "Pena de multa (dias-multa)",
    "CDC:78": "Penas restritivas de direitos",
    "CDC:79": "Fiança",
    "CDC:80": "Assistente do Ministério Público",
    # ---------------- Lavagem ----------------
    "LVD:1": "Lavagem de dinheiro (ocultação ou dissimulação de bens, direitos ou valores)",
    "LVD:1.1": "Lavagem de dinheiro – condutas equiparadas (conversão, aquisição, importação)",
    "LVD:1.2": "Lavagem de dinheiro – utilização na atividade econômica e participação em grupo",
    "LVD:1.3": "Lavagem de dinheiro – tentativa",
    "LVD:1.4": "Lavagem de dinheiro – aumento de pena (reiteração ou organização criminosa)",
    "LVD:1.5": "Lavagem de dinheiro – colaboração premiada (redução de pena)",
    "LVD:1.6": "Lavagem de dinheiro – ação controlada e infiltração de agentes",
    # ---------------- Hediondos ----------------
    "HED:1": "Rol dos crimes hediondos",
    "HED:2": "Crimes hediondos e equiparados – vedações (anistia, graça, indulto, fiança) e regime",
    # ---------------- Lei 8.137/90 ----------------
    "OTE:1": "Crime contra a ordem tributária (supressão ou redução de tributo)",
    "OTE:2": "Crime contra a ordem tributária – outras condutas (declaração falsa, não recolhimento)",
    "OTE:3": "Crime funcional contra a ordem tributária",
    "OTE:4": "Crime contra a ordem econômica (abuso do poder econômico e cartel)",
    "OTE:7": "Crime contra as relações de consumo",
    "OTE:8": "Pena de multa – fixação",
    "OTE:9": "Conversão da pena privativa de liberdade em multa",
    "OTE:10": "Elevação da pena de multa",
    "OTE:11": "Concurso de pessoas",
    "OTE:12": "Circunstâncias agravantes",
    # ---------------- Racismo ----------------
    "RAC:1": "Disposição geral – crimes de discriminação ou preconceito de raça, cor, etnia, religião ou procedência nacional",
    "RAC:2-A": "Injúria racial",
    "RAC:3": "Impedimento de acesso a cargo público por discriminação",
    "RAC:4": "Negativa de emprego em empresa privada por discriminação",
    "RAC:5": "Recusa de atendimento em estabelecimento comercial por discriminação",
    "RAC:6": "Recusa de matrícula em estabelecimento de ensino por discriminação",
    "RAC:7": "Recusa de hospedagem por discriminação",
    "RAC:8": "Recusa de atendimento em restaurantes, bares ou similares por discriminação",
    "RAC:9": "Recusa de acesso a estabelecimentos esportivos ou casas de diversão por discriminação",
    "RAC:10": "Recusa de atendimento em salões de beleza ou similares por discriminação",
    "RAC:11": "Impedimento de acesso a entradas sociais e elevadores por discriminação",
    "RAC:12": "Impedimento de uso de transportes públicos por discriminação",
    "RAC:13": "Impedimento de acesso às Forças Armadas por discriminação",
    "RAC:14": "Impedimento de casamento ou convivência familiar por discriminação",
    "RAC:16": "Efeitos da condenação (perda do cargo ou função pública)",
    "RAC:18": "Efeitos da condenação – motivação na sentença",
    "RAC:20": "Racismo (praticar, induzir ou incitar discriminação ou preconceito)",
    "RAC:20.1": "Propaganda nazista (fabricação ou veiculação de símbolos com a cruz suástica)",
    "RAC:20.2": "Racismo por meio de comunicação social ou publicação",
    "RAC:20.2-A": "Racismo em atividades esportivas, religiosas, artísticas ou culturais",
    "RAC:20.2-B": "Racismo religioso (obstar ou impedir manifestações ou práticas religiosas)",
    "RAC:20-A": "Racismo – aumento de pena em contexto de descontração, diversão ou recreação",
    "RAC:20-B": "Racismo – aumento de pena quando praticado por funcionário público",
    "RAC:20-C": "Interpretação – atitudes discriminatórias",
    "RAC:20-D": "Assistência à vítima de racismo por advogado ou defensor",
    # ---------------- Tortura ----------------
    "TOR:1": "Tortura",
    "TOR:1.1": "Tortura de pessoa presa ou sujeita a medida de segurança",
    "TOR:1.2": "Omissão diante da tortura",
    "TOR:1.3": "Tortura qualificada pelo resultado (lesão corporal grave ou morte)",
    "TOR:1.4": "Tortura – causas de aumento de pena",
    "TOR:1.5": "Tortura – efeitos da condenação (perda do cargo)",
    "TOR:1.6": "Tortura – inafiançabilidade e vedação de graça ou anistia",
    "TOR:1.7": "Tortura – regime inicial fechado",
    "TOR:2": "Extraterritorialidade da lei de tortura",
    # ---------------- Organização criminosa ----------------
    "ORC:1": "Definição de organização criminosa (disposição geral)",
    "ORC:2": "Organização criminosa (promover, constituir, financiar ou integrar)",
    "ORC:2.1": "Organização criminosa – embaraço à investigação",
    "ORC:2.2": "Organização criminosa – aumento pelo emprego de arma de fogo",
    "ORC:2.3": "Organização criminosa – agravante para quem exerce o comando",
    "ORC:2.4": "Organização criminosa – causas de aumento de pena",
    "ORC:18": "Revelação de identidade de colaborador",
    "ORC:19": "Imputação falsa sob pretexto de colaboração com a Justiça",
    "ORC:20": "Descumprimento de sigilo da investigação (ação controlada e infiltração)",
    "ORC:21": "Recusa ou omissão de dados cadastrais requisitados",
    # ---------------- Abuso de autoridade ----------------
    "ABU:9": "Decretação de privação de liberdade em desconformidade com a lei",
    "ABU:10": "Condução coercitiva descabida ou sem prévia intimação",
    "ABU:12": "Omissão de comunicação de prisão em flagrante e dos direitos do preso",
    "ABU:13": "Constrangimento do preso (exibição à curiosidade pública, situação vexatória, prova contra si)",
    "ABU:15": "Constrangimento a depor de pessoa com dever de sigilo",
    "ABU:16": "Omissão de identificação ou identificação falsa ao preso",
    "ABU:18": "Interrogatório policial durante o repouso noturno",
    "ABU:19": "Impedimento de envio de pleito do preso à autoridade judiciária",
    "ABU:20": "Impedimento de entrevista pessoal e reservada do preso com advogado",
    "ABU:21": "Manutenção de presos de ambos os sexos na mesma cela",
    "ABU:22": "Invasão de domicílio por autoridade",
    "ABU:23": "Fraude processual por autoridade (inovação do estado de lugar, coisa ou pessoa)",
    "ABU:24": "Constrangimento de funcionário de hospital para admitir pessoa já falecida",
    "ABU:25": "Obtenção de prova por meio manifestamente ilícito",
    "ABU:27": "Instauração de procedimento investigatório sem indícios",
    "ABU:28": "Divulgação de gravação sem relação com a prova",
    "ABU:29": "Informação falsa sobre procedimento para prejudicar investigado",
    "ABU:30": "Persecução penal, civil ou administrativa sem justa causa",
    "ABU:31": "Procrastinação injustificada de investigação",
    "ABU:32": "Negativa de acesso aos autos ao interessado ou advogado",
    "ABU:33": "Exigência de informação ou obrigação sem amparo legal",
    "ABU:36": "Indisponibilidade de ativos financeiros em quantia excessiva",
    "ABU:37": "Demora injustificada no exame de processo com pedido de vista",
    "ABU:38": "Antecipação de atribuição de culpa antes de concluída a investigação",
    # ---------------- Terrorismo ----------------
    "TER:2": "Terrorismo – definição e atos de terrorismo",
    "TER:2.1": "Atos de terrorismo",
    "TER:2.2": "Terrorismo – exclusão (manifestações políticas e movimentos sociais)",
    "TER:3": "Organização terrorista (promover, constituir, integrar ou prestar auxílio)",
    "TER:5": "Atos preparatórios de terrorismo",
    "TER:6": "Financiamento do terrorismo",
    "TER:7": "Terrorismo – aumento de pena pelo resultado lesão grave ou morte",
    # ---------------- Genocídio ----------------
    "GEN:1": "Genocídio",
    "GEN:2": "Associação para a prática de genocídio",
    "GEN:3": "Incitação ao genocídio",
    # ---------------- Estatuto da Pessoa Idosa ----------------
    "IDO:96": "Discriminação de pessoa idosa",
    "IDO:97": "Omissão de socorro a pessoa idosa",
    "IDO:98": "Abandono de pessoa idosa em hospitais, casas de saúde ou entidades",
    "IDO:99": "Exposição a perigo da integridade e saúde da pessoa idosa",
    "IDO:100": "Discriminação de pessoa idosa – acesso a cargo, emprego e atendimento (rol de condutas)",
    "IDO:101": "Descumprimento de ordem judicial em ação em favor de pessoa idosa",
    "IDO:102": "Apropriação ou desvio de bens ou rendimentos de pessoa idosa",
    "IDO:103": "Negativa de acolhimento por recusa de outorga de procuração",
    "IDO:104": "Retenção de cartão magnético ou documento de pessoa idosa",
    "IDO:105": "Exibição de informações ou imagens depreciativas de pessoa idosa",
    "IDO:106": "Indução de pessoa idosa sem discernimento a outorgar procuração",
    "IDO:107": "Coação de pessoa idosa a doar, contratar, testar ou outorgar procuração",
    "IDO:108": "Lavratura de ato notarial envolvendo pessoa idosa sem discernimento",
    # ---------------- Sistema Financeiro Nacional ----------------
    "SFN:2": "Impressão ou circulação de títulos sem autorização da sociedade emissora",
    "SFN:3": "Divulgação de informação falsa sobre instituição financeira",
    "SFN:4": "Gestão fraudulenta de instituição financeira",
    "SFN:4.1": "Gestão temerária de instituição financeira",
    "SFN:5": "Apropriação indébita ou desvio de valores por administrador de instituição financeira",
    "SFN:6": "Indução em erro de sócio, investidor ou repartição pública",
    "SFN:7": "Emissão ou negociação irregular de títulos ou valores mobiliários",
    "SFN:8": "Exigência de juros ou remuneração em desacordo com a legislação",
    "SFN:9": "Fraude à fiscalização ou ao investidor em documento comprobatório",
    "SFN:10": "Omissão ou inserção de elemento falso em demonstrativos contábeis",
    "SFN:11": "Contabilidade paralela (caixa dois) em instituição financeira",
    "SFN:12": "Omissão de informações ao interventor, liquidante ou síndico",
    "SFN:13": "Desvio de bem indisponível em intervenção ou liquidação",
    "SFN:14": "Declaração falsa de crédito em liquidação ou falência de instituição financeira",
    "SFN:15": "Manifestação falsa do interventor, liquidante ou síndico",
    "SFN:16": "Operação de instituição financeira sem autorização",
    "SFN:17": "Concessão de empréstimo vedado a administradores, parentes ou controladores",
    "SFN:18": "Violação de sigilo de operação ou serviço financeiro",
    "SFN:19": "Obtenção de financiamento mediante fraude",
    "SFN:20": "Desvio de finalidade de financiamento",
    "SFN:21": "Falsa identidade em operação de câmbio",
    "SFN:22": "Evasão de divisas",
    "SFN:23": "Prevaricação financeira (omissão de ato de ofício por funcionário público)",
    # ---------------- PCD / DEF ----------------
    "PCD:88": "Discriminação de pessoa com deficiência",
    "PCD:89": "Apropriação ou desvio de bens ou rendimentos de pessoa com deficiência",
    "PCD:90": "Abandono de pessoa com deficiência em hospitais ou entidades",
    "PCD:91": "Retenção de cartão magnético ou documento de pessoa com deficiência",
    "DEF:8": "Crimes contra pessoa com deficiência (recusa de matrícula, emprego ou atendimento)",
    # ---------------- Transplantes ----------------
    "TRA:14": "Remoção ilegal de tecidos, órgãos ou partes do corpo",
    "TRA:15": "Compra ou venda de tecidos, órgãos ou partes do corpo humano",
    "TRA:16": "Transplante com órgãos ou tecidos obtidos ilegalmente",
    "TRA:17": "Transporte ou guarda de partes do corpo obtidas ilegalmente",
    "TRA:18": "Transplante em desacordo com a lei (consentimento)",
    "TRA:19": "Omissão de recomposição de cadáver",
    "TRA:20": "Publicação de anúncio ou apelo público irregular sobre transplantes",
    # ---------------- Economia popular ----------------
    "EPO:2": "Crimes contra a economia popular (rol de condutas)",
    "EPO:3": "Crimes contra a economia popular – gestão fraudulenta e outras condutas",
    "EPO:4": "Usura pecuniária ou real",
    # ---------------- Parcelamento do solo ----------------
    "SOL:50": "Loteamento ou desmembramento irregular do solo urbano",
    "SOL:50.1": "Loteamento ou desmembramento irregular qualificado",
    "SOL:51": "Concurso de pessoas (mandatário, diretor ou gerente)",
    "SOL:52": "Registro de loteamento ou desmembramento não aprovado",
    # ---------------- Software ----------------
    "SOF:12": "Violação de direito autoral de programa de computador",
    "SOF:12.1": "Reprodução de programa de computador para fins de comércio",
    "SOF:12.2": "Comercialização de cópia de programa de computador produzida com violação de direito autoral",
    "SOF:12.3": "Violação de direito autoral de programa de computador – ação penal",
    # ---------------- Biossegurança ----------------
    "BIO:24": "Utilização ilegal de embrião humano",
    "BIO:25": "Engenharia genética em célula germinal, zigoto ou embrião humano",
    "BIO:26": "Clonagem humana",
    "BIO:27": "Liberação ou descarte de OGM no meio ambiente em desacordo com as normas",
    "BIO:28": "Uso de tecnologias genéticas de restrição do uso",
    "BIO:29": "Produção, comercialização ou transporte de OGM sem autorização",
    # ---------------- Interceptação ----------------
    "INT:10": "Interceptação telefônica, informática ou telemática ilegal e quebra de segredo de justiça",
    "INT:10-A": "Captação ambiental ilegal de sinais eletromagnéticos, ópticos ou acústicos",
    # ---------------- HIV ----------------
    "HIV:1": "Discriminação de portador do HIV ou doente de aids",
    # ---------------- Prefeitos ----------------
    "PRE:1": "Crimes de responsabilidade de prefeitos (rol de condutas)",
    "PRE:1.1": "Crimes de responsabilidade de prefeitos – penas",
    "PRE:1.2": "Crimes de responsabilidade de prefeitos – efeitos da condenação (perda do cargo e inabilitação)",
    # ---------------- Discriminação no trabalho ----------------
    "DIS:2": "Práticas discriminatórias no trabalho (exigência de teste de gravidez ou esterilização)",
    # ---------------- Código Eleitoral ----------------
    "ELE:289": "Inscrição fraudulenta de eleitor",
    "ELE:290": "Induzimento à inscrição fraudulenta de eleitor",
    "ELE:291": "Inscrição fraudulenta efetuada pelo juiz",
    "ELE:292": "Negativa ou retardamento de inscrição eleitoral",
    "ELE:293": "Perturbação ou impedimento do alistamento",
    "ELE:295": "Retenção de título eleitoral",
    "ELE:296": "Promoção de desordem nos trabalhos eleitorais",
    "ELE:297": "Impedimento ou embaraço ao exercício do sufrágio",
    "ELE:298": "Prisão ou detenção ilegal de eleitor, membro de mesa ou candidato",
    "ELE:299": "Corrupção eleitoral (compra de votos)",
    "ELE:300": "Coação eleitoral por servidor público",
    "ELE:301": "Coação eleitoral mediante violência ou grave ameaça",
    "ELE:302": "Concentração de eleitores no dia da eleição (transporte e alimentação)",
    "ELE:303": "Majoração de preços de utilidades e serviços no dia da eleição",
    "ELE:304": "Sonegação de utilidades no dia da eleição",
    "ELE:305": "Intervenção de autoridade estranha à mesa receptora",
    "ELE:306": "Inobservância da ordem de votação",
    "ELE:307": "Fornecimento de cédula já assinalada",
    "ELE:308": "Fornecimento irregular de cédula oficial",
    "ELE:309": "Votar mais de uma vez ou em lugar de outrem",
    "ELE:310": "Irregularidade na recepção de votos",
    "ELE:311": "Votar em seção em que não está inscrito",
    "ELE:312": "Violação do sigilo do voto",
    "ELE:313": "Omissão de expedição do boletim de apuração",
    "ELE:314": "Omissão de recolhimento de cédulas apuradas",
    "ELE:315": "Alteração de mapas ou boletins de apuração",
    "ELE:316": "Omissão de protestos nas atas de eleição ou apuração",
    "ELE:317": "Violação do sigilo da urna ou dos invólucros",
    "ELE:318": "Contagem irregular de votos sob impugnação",
    "ELE:319": "Subscrição de mais de uma ficha de registro de partido",
    "ELE:320": "Inscrição simultânea em dois ou mais partidos",
    "ELE:321": "Colheita de assinatura em mais de uma ficha de registro de partido",
    "ELE:323": "Divulgação de fatos inverídicos na propaganda eleitoral",
    "ELE:324": "Calúnia eleitoral",
    "ELE:325": "Difamação eleitoral",
    "ELE:326": "Injúria eleitoral",
    "ELE:326-A": "Denunciação caluniosa com finalidade eleitoral",
    "ELE:326-B": "Violência política de gênero (assédio ou constrangimento de candidata)",
    "ELE:327": "Crimes contra a honra eleitorais – causas de aumento de pena",
    "ELE:330": "Reparação do dano antes da sentença – redução de pena",
    "ELE:331": "Inutilização ou perturbação de meio de propaganda eleitoral",
    "ELE:332": "Impedimento do exercício de propaganda eleitoral",
    "ELE:334": "Uso de organização comercial para propaganda eleitoral",
    "ELE:335": "Propaganda eleitoral em língua estrangeira",
    "ELE:336": "Sentença condenatória – efeitos nos crimes de propaganda",
    "ELE:338": "Omissão de prioridade postal eleitoral",
    "ELE:339": "Destruição ou ocultação de urna ou documentos eleitorais",
    "ELE:340": "Fabricação ou guarda irregular de urna ou cédula",
    "ELE:341": "Retardamento de publicação oficial de atos eleitorais",
    "ELE:342": "Omissão do Ministério Público em oferecer denúncia",
    "ELE:343": "Descumprimento pelo juiz do prazo de remessa de recurso",
    "ELE:344": "Recusa ou abandono do serviço eleitoral",
    "ELE:345": "Descumprimento de prazos pela autoridade ou funcionário da Justiça Eleitoral",
    "ELE:346": "Violação da proibição de uso de serviços públicos em propaganda",
    "ELE:347": "Desobediência à Justiça Eleitoral",
    "ELE:348": "Falsificação de documento público para fins eleitorais",
    "ELE:349": "Falsificação de documento particular para fins eleitorais",
    "ELE:350": "Falsidade ideológica eleitoral",
    "ELE:351": "Equiparação a documento para fins penais eleitorais",
    "ELE:353": "Uso de documento falso para fins eleitorais",
    "ELE:354": "Obtenção de documento falso para fins eleitorais",
    "ELE:354-A": "Apropriação indébita eleitoral (recursos de campanha)",
    # ---------------- Propriedade industrial ----------------
    "PIN:183": "Crime contra patente (fabricação de produto ou uso de processo patenteado)",
    "PIN:184": "Crime contra patente (comercialização de produto patenteado)",
    "PIN:185": "Fornecimento de componente para produto patenteado",
    "PIN:186": "Caracterização dos crimes contra patente",
    "PIN:187": "Fabricação de produto com desenho industrial registrado sem autorização",
    "PIN:188": "Crime contra registro de desenho industrial (comercialização)",
    "PIN:189": "Crime contra registro de marca (reprodução ou imitação)",
    "PIN:190": "Crime contra registro de marca (comercialização)",
    "PIN:191": "Uso indevido de armas, brasões ou distintivos oficiais",
    "PIN:192": "Falsa indicação geográfica",
    "PIN:193": "Uso de falsa indicação geográfica ou de certificação em produto",
    "PIN:194": "Uso de marca ou sinal com falsa indicação de procedência",
    "PIN:195": "Concorrência desleal",
    # ---------------- CVM ----------------
    "CVM:27-F": "Crimes contra o mercado de capitais – aplicação das multas",
    # ---------------- Henry Borel / Maria da Penha ----------------
    "HBO:25": "Descumprimento de medida protetiva de urgência (Lei Henry Borel)",
    "MDP:5": "Definição de violência doméstica e familiar contra a mulher",
    "MDP:7": "Formas de violência doméstica e familiar contra a mulher",
    "MDP:24-A": "Descumprimento de medidas protetivas de urgência",
    "MDP:24-A.4": "Descumprimento de medidas protetivas – violação de monitoramento eletrônico (aumento)",
}

# Tipo forçado por idUnico (quando a regra automática não basta)
TIPO = {
    "DRG:28": "crime",
    "CTB:165": "disposicao",
    "HED:1": "disposicao",
    "HED:2": "disposicao",
}

# Pena (penaMin, penaMax) forçada
PENA = {
    "DRG:28": ("Advertência, prestação de serviços à comunidade ou medida educativa", ""),
    "OTE:3": ("Reclusão, de 1 a 4 anos", "e multa"),
}

DESC.update({
    "CP:14": "Crime consumado e crime tentado",
    "CP:14.1": "Pena de tentativa",
    "CP:18": "Crime doloso e crime culposo",
    "CP:29": "Concurso de pessoas",
    "CP:32": "Espécies de pena",
    "CP:44": "Penas restritivas de direitos – substituição da pena privativa de liberdade",
    "CP:55": "Penas restritivas de direitos – duração",
    "CP:56": "Penas de interdição temporária de direitos (cargo, função ou atividade)",
    "CP:57": "Pena de interdição – suspensão de autorização ou habilitação para dirigir",
    "CP:64": "Reincidência – prazo depurador e crimes militares ou políticos",
    "CP:66": "Atenuante inominada",
    "CP:78": "Suspensão condicional da pena – condições",
    "CP:79": "Suspensão condicional da pena – outras condições",
    "CP:80": "Suspensão condicional da pena – não extensão a penas restritivas e multa",
    "CP:90": "Livramento condicional – extinção da pena",
    "CP:91-A": "Perda alargada de bens (confisco alargado)",
    "CP:92": "Efeitos da condenação (perda de cargo, poder familiar, inabilitação para dirigir)",
    "CP:94": "Reabilitação – requisitos",
    "CP:95": "Reabilitação – revogação",
    "CP:106": "Perdão do ofendido",
    "CP:108": "Extinção da punibilidade de crime pressuposto, elemento ou circunstância",
    "CP:118": "Prescrição – penas mais leves",
    "CP:119": "Prescrição – concurso de crimes",
    "DES:19": "Comércio ilegal e tráfico internacional de armas – aumento (arma de uso restrito)",
    "DES:20": "Crimes do Estatuto do Desarmamento – aumento (agente de segurança)",
})
